# Note: the baseurl used must match that on GitHub, which they pick as being
# the name of the repo.
baseurl: /competition-website
url: https://studentrobotics.org

# We don't currently have teams-status pages, when they reappear uncomment
# the following line
# teams_url: https://studentrobotics.org/teams

title: Student Robotics
description: >
  Student Robotics is an exciting annual competition challenging people aged
  16-18 to assemble a team and build fully autonomous robots.

year: 2021
api_root: https://studentrobotics.org/comp-api

competition_link: https://studentrobotics.org/events/sr2021/knockouts/
youtube_stream_link: https://www.youtube-nocookie.com/embed/gxJM6ernMqo

links:
  donate: //link.justgiving.com/v1/charity/donate/charityId/3118662?tipScheme=TipJar2.1&isRecurring=true&amount=20.00&reference=givingcheckout_tj21

markdown: kramdown

timezone: Etc/GMT

social:
  - title: GitHub
    icon: github
    link: https://github.com/srobo
  - title: Twitter
    icon: twitter
    link: https://twitter.com/studentrobotics
  - title: YouTube
    icon: youtube-play
    link: https://youtube.com/user/StudentRobotics
  - title: Instagram
    icon: instagram
    link: https://www.instagram.com/student_robotics/
  - title: Facebook
    icon: facebook-official
    link: https://facebook.com/StudentRobotics
  - title: LinkedIn
    icon: linkedin
    link: https://www.linkedin.com/company/10969472/

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - gems/
  - vendor/
