baseurl: /comp
url: https://studentrobotics.org

title: Student Robotics
description: >
  Student Robotics is an exciting annual competition challenging people aged
  16-18 to assemble a team and build fully autonomous robots.

year: 2016
api_root: /comp-api

markdown: kramdown

timezone: Etc/GMT

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - gems/
