# Note: the baseurl used must match that on GitHub, which they pick as being
# the name of the repo.
baseurl: /competition-website
url: https://studentrobotics.org

# We don't currently have teams-status pages, when they reappear uncomment
# the following line
# teams_url: https://studentrobotics.org/teams

title: Student Robotics
description: >
  Student Robotics is an exciting annual competition challenging people aged
  16-18 to assemble a team and build fully autonomous robots.

year: 2017
api_root: https://studentrobotics.org/comp-api

competition_link: https://studentrobotics.org/events/sr2017/competition/
youtube_stream_link: https://www.youtube-nocookie.com/embed/KVWdpv82kUU
venue_layout_link: https://studentrobotics.org/resources/2016/competition-layout.pdf

markdown: kramdown

timezone: Etc/GMT

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - gems/
